select 
HEALTHREGISTRATIONID			as [SanitaryRegistryId],
SACITEMID						as [SACItemId],
ELOGITEMID						as [ELOGItemId],
ITEMID							as [ItemId],
REGISTRATIONCOUNTRYREGIONID		as [CountryRegionRegistryId],
REGISTRATIONDATE				as [SanitaryRegistryDate],
HEALTHREGISTRATIONMERLINID		as [MerlinId],
REGISTRATIONDUEDATE				as [DueDate],
REGISTRATIONDUEDATEEXTDATE		as [DueDateExtDate],
REGISTRATIONDUEDATEEXTID		as [DueDateExtId],
REGISTRATIONDUEDATEEXTAPP40011	as [DueDateExtApprovalDate],
ITEMNAME						as [ItemName],
HEALTHREGISTRATIONMANUFACTURER	as [Manufacturer],
HEALTHREGISTRATIONSTATUS		as [Status],
HEALTHREGISTRATIONSTATUSDESC	as [StatusDesc],
COUNTRYREGIONIDMANUFACTURER		as [CountryRegionProducerId],
HEALTHREGISTRATIONDESC			as [Description]
from HEALTHREGISTRATION_MPH
where DATAAREAID = '120'
