select INVENTTRANS.ITEMID, INVENTTRANS.QTY, INVENTTRANS.TRANSREFID,
--onorder, reservphysical,((AVAILPHYSICAL % 1) * 100 % 1),(AVAILPHYSICAL % 1),AVAILPHYSICAL, 
INVENTDIM.INVENTLOCATIONID,
INVENTDIM.INVENTBATCHID,
INVENTDIM.WMSLOCATIONID,
INVENTDIM.INVENTLEGALNUMID,
INVENTDIM.INVENTCONTAINERID,
INVENTDIM.INVENTSUBBATCHID,
INVENTTRANS.*  from INVENTTRANS, INVENTDIM, INVENTTABLEMODULE
where INVENTTRANS.DATAAREAID = '070'
and INVENTTRANS.DATAAREAID = INVENTDIM.DATAAREAID
and INVENTTRANS.INVENTDIMID = INVENTDIM.INVENTDIMID
and INVENTTRANS.DATAAREAID = INVENTTABLEMODULE.DATAAREAID
and INVENTTRANS.ITEMID = INVENTTABLEMODULE.ITEMID
and INVENTTABLEMODULE.moduletype = 0
--and AVAILPHYSICAL > 0
--and ITEMID = '50022'
--and ((AVAILPHYSICAL % 1) * 100 % 1) > 0
--and ((RESERVPHYSICAL % 1) * 100 % 1) > 0
--and RESERVPHYSICAL = 0 
--and ((ONORDER % 1) * 100 % 1) > 0
--and onorder > 0 
and abs((QTY % 1) * 100 % 1) <> 0
--and qty < 0 
and DATEPHYSICAL = '1900-01-01'
--and INVENTTRANS.ITEMID = '59015'
--and INVENTTRANS.STATUSISSUE = 4
order by INVENTTRANS.ITEMID, INVENTTRANS.TRANSREFID